dev-cmp04.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp06.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp07.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp08.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp09.int.na.getgooddata.com:
  :roles:
    - compute
    - dqa
dev-cmp10.int.na.getgooddata.com:
  :roles:
    - compute
    - dqa
prod-cmp01.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp02.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp03.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp04.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp05.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp06.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp07.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp08.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp09.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp10.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp11.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp12.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp13.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp14.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp15.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp16.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp17.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp18.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp19.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp20.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp21.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp22.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp23.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp24.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp25.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp26.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp27.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp28.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp29.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp30.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp31.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp32.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp33.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp34.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp35.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp36.int.na.getgooddata.com:
  :roles:
    - compute
    - prod02
prod-cmp37.int.na.getgooddata.com:
  :roles:
    - compute
    - prod02
prod-cmp38.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp39.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp40.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp41.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp42.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp43.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp44.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp45.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
prod-cmp46.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
prod-cmp47.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp48.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
prod-cmp49.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
prod-cmp50.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
prod-cmp51.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp52.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp53.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp54.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp55.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp56.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp57.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp58.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp59.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp60.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp61.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp62.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp63.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp64.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp65.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp66.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp67.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp68.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp69.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp70.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp71.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp72.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp73.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp74.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp75.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
