dev-cmp04.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp06.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp07.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp08.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
dev-cmp09.int.na.getgooddata.com:
  :roles:
    - compute
    - dqa
dev-cmp10.int.na.getgooddata.com:
  :roles:
    - compute
    - dqa
prod-cmp01.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp02.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp03.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp04.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp05.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp06.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp07.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp08.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp09.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp10.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp11.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp12.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp13.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp14.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp15.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp16.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp17.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp18.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp19.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp20.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp21.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp22.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp23.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp24.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp25.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp26.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp27.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
  :tags:
    - crypt
prod-cmp28.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp29.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp30.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp31.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp32.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720
prod-cmp33.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp34.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp35.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp36.int.na.getgooddata.com:
  :roles:
    - compute
    - prod02
  :tags:
    - crypt
prod-cmp37.int.na.getgooddata.com:
  :roles:
    - compute
    - prod02
  :tags:
    - crypt
prod-cmp38.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp39.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp40.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp41.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp42.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp43.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp44.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp45.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
  :tags:
    - crypt
prod-cmp46.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r820
  :tags:
    - crypt
prod-cmp47.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp48.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
  :tags:
    - crypt
prod-cmp49.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
  :tags:
    - crypt
prod-cmp50.int.na.getgooddata.com:
  :roles:
    - compute
    - prod01
  :tags:
    - crypt
prod-cmp51.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp52.int.na.getgooddata.com:
  :roles:
    - compute
    - dev
prod-cmp53.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp54.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp55.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp56.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp57.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp58.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp59.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp60.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp61.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp62.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
prod-cmp63.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp64.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp65.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp66.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp67.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720b
  :tags:
    - crypt
prod-cmp68.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp69.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp70.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp71.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp72.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp73.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp74.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp75.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp76.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp77.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp78.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp79.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp80.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp81.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp82.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp83.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp84.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp85.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp86.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp87.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp88.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp89.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp90.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp91.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp92.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp93.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp94.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp95.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp96.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
  :tags:
    - crypt
prod-cmp97.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp98.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp99.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp100.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp101.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp102.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp103.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp104.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp105.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp106.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp107.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
172.30.64.108:
  :roles:
    - baremetal
172.30.64.109:
  :roles:
    - baremetal
172.30.64.110:
  :roles:
    - baremetal
172.30.64.111:
  :roles:
    - baremetal
172.30.64.112:
  :roles:
    - baremetal
prod-cmp113.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp114.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp115.int.na.getgooddata.com:
  :roles:
    - compute
    - prod03
  :tags:
    - crypt
prod-cmp116.int.na.getgooddata.com:
  :roles:
    - compute
    - prod03
  :tags:
    - crypt
prod-cmp117.int.na.getgooddata.com:
  :roles:
    - compute
    - perf
  :tags:
    - crypt
prod-cmp118.int.na.getgooddata.com:
  :roles:
    - compute
    - perf
  :tags:
    - crypt
prod-cmp119.int.na.getgooddata.com:
  :roles:
    - compute
    - perf
  :tags:
    - crypt
prod-cmp120.int.na.getgooddata.com:
  :roles:
    - compute
    - perf
  :tags:
    - crypt
prod-cmp121.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp122.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp123.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp124.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
prod-cmp125.int.na.getgooddata.com:
  :roles:
    - compute
    - dwh_r720xd
mgmt04.na.getgooddata.com:
  :roles:
    - nova_management
mgmt05.na.getgooddata.com:
  :roles:
    - nova_management
mgmt-backend01.na.getgooddata.com:
  :roles:
    - mgmt_backend
mgmt-glance01.na.getgooddata.com:
  :roles:
    - mgmt_glance
mgmt-netapp01.na.getgooddata.com:
  :roles:
    - mgmt_netapp
mgmt-repo.na.getgooddata.com:
  :roles:
    - mgmt_repo
deploy.na.getgooddata.com:
  :roles:
    - mgmt_deploy
mgmt-serverspec.na.getgooddata.com:
  :roles:
    - mgmt_serverspec
mgmt-test01.na.getgooddata.com:
  :roles:
    - mgmt_test
mgmt-apiserver01.na.getgooddata.com:
  :roles:
    - mgmt_api_server
mgmt-apiserver02.na.getgooddata.com:
  :roles:
    - mgmt_api_server
mgmt-apiproxy01.na.getgooddata.com:
  :roles:
    - mgmt_api_proxy
